# Generated by Django 5.2.7 on 2026-01-04 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapaymentrequest',
            name='transaction_id',
            field=models.IntegerField(blank=True, help_text='Transaction ID for frontend reference', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.IntegerField(blank=True, help_text='Transaction ID for frontend reference', null=True),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transaction_id'], name='payments_mp_transac_f38b62_idx'),
        ),
    ]
