"""
Django settings for DC_BACKEND project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""
import os
from pathlib import Path
from datetime import timedelta
from decimal import Decimal
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
SECRET_KEY = 'django-insecure-=7#lf2y8t#a!a$ii1+csnbui9v7^ej-ownq0v5_rab#g#)w_7d'
DEBUG = True
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'dc-backend-6xlc.onrender.com',
    '0.0.0.0',
    '192.168.100.38',
    '*'
]



# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
    'rest_framework_simplejwt',
    
    # Local apps
    'accounts',
    'categories',
    'payments',
    'dashboard',
    'calls',
    'admin_dashboard',  # Your new admin dashboard app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DC_BACKEND.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DC_BACKEND.wsgi.application'
ASGI_APPLICATION = 'DC_BACKEND.asgi.application'


# Add at the TOP of settings.py
import socket
socket.getaddrinfo('db.tssyexupvlvtvvxdhhba.supabase.co', 5432)

# Database config
# Database config - Render PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dc_website',
        'USER': 'dc_website_user',
        'PASSWORD': 'f2Y0bOytWxxoh1l5N5LztDyoapi9ZejQ',
        'HOST': 'dpg-d5j7nnffte5s73d7olj0-a.oregon-postgres.render.com',
        'PORT': 5432,
        'OPTIONS': {'sslmode': 'require'}
    }
}
# Redis for WebSockets (optional, comment out if not using)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Use this for development
        # For production:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development

# OR if you want specific origins:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://192.168.100.38:5173",
#     "http://localhost:5173",
# ]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Authentication URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/professional/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Security settings (for production)
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# =========================================================================
# M-PESA CONFIGURATION - KEEP INTACT
# =========================================================================

MPESA_CONFIG = {
    'environment': config('MPESA_ENVIRONMENT', default='sandbox'),
    'consumer_key': config('MPESA_CONSUMER_KEY', default='AUJGjjBscXAZUF6sENrFb58aWchWXsfG7XJ5DipNMWBPsqgj'),
    'consumer_secret': config('MPESA_CONSUMER_SECRET', default='va2IOGXwsD4BMpGe0iPQdO9h14Aoj53koEnhxA1P7RSO0WgIIz03Y2mxLHPQugbS'),
    'business_shortcode': config('MPESA_BUSINESS_SHORTCODE', default='174379'),
    'passkey': config('MPESA_PASSKEY', default='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'),
    'callback_url': config('MPESA_CALLBACK_URL', default='http://dc-backend-6xlc.onrender.com/api/payments/mpesa/callback/'),
}

# Simplified M-Pesa variables for backward compatibility
MPESA_ENVIRONMENT = MPESA_CONFIG['environment']
MPESA_CONSUMER_KEY = MPESA_CONFIG['consumer_key']
MPESA_CONSUMER_SECRET = MPESA_CONFIG['consumer_secret']
MPESA_BUSINESS_SHORTCODE = MPESA_CONFIG['business_shortcode']
MPESA_PASSKEY = MPESA_CONFIG['passkey']
MPESA_CALLBACK_URL = MPESA_CONFIG['callback_url']

# =========================================================================
# BACKWARD COMPATIBILITY - ADD THESE LINES
# =========================================================================
MPESA_SANDBOX_CONSUMER_KEY = MPESA_CONFIG['consumer_key']
MPESA_SANDBOX_CONSUMER_SECRET = MPESA_CONFIG['consumer_secret']
MPESA_SANDBOX_PASSKEY = MPESA_CONFIG['passkey']
MPESA_SANDBOX_SHORTCODE = MPESA_CONFIG['business_shortcode']
MPESA_SANDBOX_PARTYB = MPESA_CONFIG['business_shortcode']

MPESA_PRODUCTION_CONSUMER_KEY = MPESA_CONFIG['consumer_key']
MPESA_PRODUCTION_CONSUMER_SECRET = MPESA_CONFIG['consumer_secret']
MPESA_PRODUCTION_PASSKEY = MPESA_CONFIG['passkey']
MPESA_PRODUCTION_SHORTCODE = MPESA_CONFIG['business_shortcode']
MPESA_PRODUCTION_PARTYB = MPESA_CONFIG['business_shortcode']

# =========================================================================
# PAYMENT CONFIGURATION
# =========================================================================

# Callback URLs (Updated for your local IP)
BASE_URL = 'http://dc-backend-6xlc.onrender.com'  # Your actual IP address
MPESA_PAYMENT_TIMEOUT = 10  # minutes

# Stripe Settings
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', 'sk_test_...')  # Your test key
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', 'pk_test_...')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Platform Fees
PLATFORM_FEE_PERCENTAGE = Decimal('20.00')  # 20%
PROCESSING_FEE_PERCENTAGE = Decimal('2.90')  # 2.9%
PROCESSING_FEE_FIXED = Decimal('0.30')  # $0.30

# Payout Settings
MINIMUM_PAYOUT_AMOUNT = Decimal('10.00')  # $10 minimum
PAYOUT_SCHEDULE = 'weekly'  # weekly, biweekly, monthly
PAYOUT_PROCESSING_DAYS = 3  # Days to process payouts

# Session Settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True

# Email Configuration (for production)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
# For production:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'


# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Cache settings (for production)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }

# Cache timeout
CACHE_TIMEOUT = 300  # 5 minutes

# =========================================================================
# DEBUG: Print M-Pesa configuration (remove in production)
# =========================================================================
print("=" * 50)
print("M-PESA CONFIGURATION CHECK")
print("=" * 50)
print(f"Environment: {MPESA_ENVIRONMENT}")
print(f"Consumer Key: {'✓ SET' if MPESA_CONSUMER_KEY else '✗ EMPTY'}")
print(f"Consumer Secret: {'✓ SET' if MPESA_CONSUMER_SECRET else '✗ EMPTY'}")
print(f"Business Shortcode: {MPESA_BUSINESS_SHORTCODE}")
print(f"Passkey: {'✓ SET' if MPESA_PASSKEY else '✗ EMPTY'}")
print(f"Callback URL: {MPESA_CALLBACK_URL}")
print(f"Base URL: {BASE_URL}")
print("=" * 50)



# =========================================================================
# AUTO-CREATE ADMIN USER
# =========================================================================
import os
from django.contrib.auth import get_user_model

if os.environ.get('RENDER'):
    try:
        User = get_user_model()
        if not User.objects.filter(username='admin').exists():
            admin = User.objects.create_superuser(
                username='admin',
                email='admin@directconnect.com',
                password='admin123'
            )
            print("=" * 50)
            print("✅ ADMIN USER CREATED")
            print(f"Username: admin")
            print(f"Email: admin@directconnect.com")
            print(f"Password: admin123")
            print("=" * 50)
        else:
            print("✅ Admin user already exists")
    except Exception as e:
        print("=" * 50)
        print("❌ FAILED TO CREATE ADMIN USER")
        print(f"Error: {e}")
        print("=" * 50)
