# Generated by Django 5.2.7 on 2026-01-01 02:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, help_text='Overall availability status')),
                ('auto_accept_calls', models.BooleanField(default=False, help_text='Automatically accept incoming calls')),
                ('max_daily_sessions', models.IntegerField(default=8, help_text='Maximum number of sessions per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('working_hours_start', models.TimeField(default='09:00:00')),
                ('working_hours_end', models.TimeField(default='17:00:00')),
                ('break_duration_minutes', models.IntegerField(default=60, help_text='Break duration in minutes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)])),
                ('break_start_time', models.TimeField(default='13:00:00')),
                ('buffer_minutes', models.IntegerField(default=15, help_text='Buffer time between sessions (minutes)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('available_days', models.JSONField(default=dict, help_text='JSON object with day availability')),
                ('timezone', models.CharField(default='UTC', help_text="Professional's timezone", max_length=50)),
                ('schedule_exceptions', models.JSONField(default=list, help_text='List of date-specific schedule exceptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.professionalprofile', verbose_name='Professional')),
            ],
            options={
                'verbose_name': 'Professional Availability',
                'verbose_name_plural': 'Professional Availabilities',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consultations', models.IntegerField(default=0)),
                ('completed_consultations', models.IntegerField(default=0)),
                ('pending_consultations', models.IntegerField(default=0)),
                ('cancelled_consultations', models.IntegerField(default=0)),
                ('today_consultations', models.IntegerField(default=0)),
                ('today_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('today_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('week_consultations', models.IntegerField(default=0)),
                ('week_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('week_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('month_consultations', models.IntegerField(default=0)),
                ('month_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('month_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('response_time_minutes', models.IntegerField(default=0)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('top_categories', models.JSONField(default=list, help_text='JSON array of top consultation categories')),
                ('busiest_days', models.JSONField(default=list, help_text='JSON array of busiest days')),
                ('busiest_hours', models.JSONField(default=list, help_text='JSON array of busiest hours')),
                ('earnings_by_category', models.JSONField(default=dict, help_text='JSON object of earnings by category')),
                ('earnings_by_month', models.JSONField(default=dict, help_text='JSON object of earnings by month')),
                ('repeat_clients', models.IntegerField(default=0)),
                ('client_satisfaction_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stats_since', models.DateTimeField(auto_now_add=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.professionalprofile', verbose_name='Professional')),
            ],
            options={
                'verbose_name': 'Professional Statistic',
                'verbose_name_plural': 'Professional Statistics',
            },
        ),
        migrations.CreateModel(
            name='IncomingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Expected duration in minutes')),
                ('estimated_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Call expiration time')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to='categories.consultationrequest', verbose_name='Consultation')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to='accounts.professionalprofile', verbose_name='Professional')),
            ],
            options={
                'verbose_name': 'Incoming Call',
                'verbose_name_plural': 'Incoming Calls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='dashboard_i_status_851642_idx'), models.Index(fields=['professional', 'status'], name='dashboard_i_profess_5e9e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('incoming_call', 'Incoming Call'), ('consultation_update', 'Consultation Update'), ('payment', 'Payment'), ('rating', 'Rating'), ('promotion', 'Promotion'), ('announcement', 'Announcement'), ('reminder', 'Reminder')], default='system', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='0=Low, 1=Normal, 2=High, 3=Urgent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'), models.Index(fields=['created_at'], name='dashboard_n_created_526fd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('consultation', 'Consultation'), ('break', 'Break'), ('busy', 'Busy'), ('holiday', 'Holiday'), ('training', 'Training'), ('other', 'Other')], default='consultation', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('is_virtual', models.BooleanField(default=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remind_minutes_before', models.IntegerField(default=15, help_text='Reminder minutes before event')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='categories.consultationrequest')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.professionalprofile', verbose_name='Professional')),
            ],
            options={
                'verbose_name': 'Professional Calendar Event',
                'verbose_name_plural': 'Professional Calendar Events',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['professional', 'start_time'], name='dashboard_p_profess_3d9be8_idx'), models.Index(fields=['start_time', 'end_time'], name='dashboard_p_start_t_c22206_idx')],
            },
        ),
    ]
