# Generated by Django 5.2.7 on 2026-01-04 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
        ('calls', '0001_initial'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('call_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Call Histories',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('incoming_call', 'Incoming Call'), ('consultation_update', 'Consultation Update'), ('payment', 'Payment'), ('rating', 'Rating'), ('promotion', 'Promotion'), ('announcement', 'Announcement'), ('reminder', 'Reminder')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='incomingcall',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='professionalavailability',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professionalcalendar',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='professionalstat',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='incomingcall',
            name='dashboard_i_status_851642_idx',
        ),
        migrations.RemoveIndex(
            model_name='incomingcall',
            name='dashboard_i_profess_5e9e95_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalcalendar',
            name='dashboard_p_profess_3d9be8_idx',
        ),
        migrations.RemoveIndex(
            model_name='professionalcalendar',
            name='dashboard_p_start_t_c22206_idx',
        ),
        migrations.RemoveField(
            model_name='professionalavailability',
            name='schedule_exceptions',
        ),
        migrations.RemoveField(
            model_name='professionalstat',
            name='stats_since',
        ),
        migrations.AddField(
            model_name='incomingcall',
            name='call_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalavailability',
            name='next_available_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalcalendar',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='professionalstat',
            name='stats_date',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomingcall',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.consultation'),
        ),
        migrations.AlterField(
            model_name='incomingcall',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='incomingcall',
            name='estimated_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='incomingcall',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incomingcall',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_incoming_calls', to='accounts.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='incomingcall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='auto_accept_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='available_days',
            field=models.JSONField(default=dict, help_text='JSON of available days'),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='break_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='max_daily_sessions',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='professional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_availability', to='accounts.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='professionalavailability',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalcalendar',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.consultation'),
        ),
        migrations.AlterField(
            model_name='professionalcalendar',
            name='event_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('break', 'Break'), ('busy', 'Busy'), ('holiday', 'Holiday'), ('training', 'Training'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='professionalcalendar',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professionalcalendar',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_calendar_events', to='accounts.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='professionalcalendar',
            name='remind_minutes_before',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='professionalcalendar',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='busiest_days',
            field=models.JSONField(default=list, help_text='JSON list of busiest days'),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='busiest_hours',
            field=models.JSONField(default=list, help_text='JSON list of busiest hours'),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='cancelled_consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='completed_consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='earnings_by_category',
            field=models.JSONField(default=dict, help_text='JSON of earnings by category'),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='earnings_by_month',
            field=models.JSONField(default=dict, help_text='JSON of earnings by month'),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='month_consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='pending_consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='professional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to='accounts.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='repeat_clients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='response_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='today_consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='top_categories',
            field=models.JSONField(default=list, help_text='JSON list of top categories'),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='total_consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professionalstat',
            name='week_consultations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.consultation'),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_call_history', to='accounts.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
