# Generated by Django 5.2.7 on 2026-01-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_callhistory_professionalnotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingcall',
            name='consultation',
        ),
        migrations.AddField(
            model_name='incomingcall',
            name='consultation_id',
            field=models.IntegerField(blank=True, help_text='ID of the consultation from any app', null=True),
        ),
    ]
