# Generated by Django 5.2.7 on 2026-01-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
        ('dashboard', '0003_remove_incomingcall_consultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text="Client's unique ID", max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('call_type', models.CharField(choices=[('voice', 'Voice Call'), ('video', 'Video Call')], default='video', max_length=20)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('consultation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(default='Consultation', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('ended', 'Ended'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('room_id', models.CharField(blank=True, help_text='Zego room ID for the call', max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('call_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_call_requests', to='accounts.professionalprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
