# Generated by Django 5.2.7 on 2026-01-01 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='categories.servicecategory'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
