# Generated by Django 5.2.7 on 2026-01-06 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Template content with {{ variables }}')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_professionals', models.IntegerField(default=0)),
                ('new_professionals', models.IntegerField(default=0)),
                ('online_professionals', models.IntegerField(default=0)),
                ('verified_professionals', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('new_clients', models.IntegerField(default=0)),
                ('active_clients', models.IntegerField(default=0)),
                ('total_consultations', models.IntegerField(default=0)),
                ('new_consultations', models.IntegerField(default=0)),
                ('completed_consultations', models.IntegerField(default=0)),
                ('cancelled_consultations', models.IntegerField(default=0)),
                ('active_consultations', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('professional_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_consultation_duration', models.FloatField(default=0)),
                ('average_response_time', models.FloatField(default=0)),
                ('client_satisfaction_score', models.FloatField(default=0)),
                ('professional_satisfaction_score', models.FloatField(default=0)),
                ('consultation_conversion_rate', models.FloatField(default=0)),
                ('professional_verification_rate', models.FloatField(default=0)),
                ('client_retention_rate', models.FloatField(default=0)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('hourly_breakdown', models.JSONField(blank=True, default=dict)),
                ('device_breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Analytics',
                'verbose_name_plural': 'Platform Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Log', 'verbose_name_plural': 'Admin Logs'},
        ),
        migrations.AlterModelOptions(
            name='platformsettings',
            options={'ordering': ['category', 'key'], 'verbose_name': 'Platform Setting', 'verbose_name_plural': 'Platform Settings'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='adminlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('payments', 'Payments'), ('notifications', 'Notifications'), ('consultations', 'Consultations'), ('security', 'Security'), ('appearance', 'Appearance')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this setting can be accessed via API'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Whether this setting must have a value'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_value',
            field=models.CharField(blank=True, help_text='Maximum value (for numeric settings)', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='min_value',
            field=models.CharField(blank=True, help_text='Minimum value (for numeric settings)', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Allowed options (for select fields)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='setting_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if report generation failed'),
        ),
        migrations.AddField(
            model_name='report',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='report',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL to download the report'),
        ),
        migrations.AddField(
            model_name='report',
            name='filters',
            field=models.JSONField(blank=True, default=dict, help_text='Filters applied to generate this report'),
        ),
        migrations.AddField(
            model_name='report',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Additional parameters for report generation'),
        ),
        migrations.AddField(
            model_name='report',
            name='processing_time',
            field=models.FloatField(default=0, help_text='Time taken to generate report in seconds'),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, help_text='Report summary/executive overview'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('professional_verified', 'Professional Verified'), ('consultation_created', 'Consultation Created'), ('consultation_updated', 'Consultation Updated'), ('payment_processed', 'Payment Processed'), ('system_settings_changed', 'System Settings Changed'), ('login', 'Admin Login'), ('logout', 'Admin Logout'), ('report_generated', 'Report Generated'), ('settings_updated', 'Settings Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this setting controls'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='key',
            field=models.CharField(help_text="Setting key (e.g., 'site_name', 'commission_rate')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='value',
            field=models.JSONField(help_text='Setting value (can be string, number, boolean, or JSON)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Report data in JSON format'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to generated report file', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('revenue', 'Revenue Report'), ('users', 'User Growth Report'), ('consultations', 'Consultation Report'), ('professionals', 'Professional Performance'), ('clients', 'Client Retention'), ('platform_health', 'Platform Health'), ('financial', 'Financial Summary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['action', 'created_at'], name='admin_dashb_action_8246ce_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin', 'created_at'], name='admin_dashb_admin_i_3bfa65_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsettings',
            index=models.Index(fields=['category', 'key'], name='admin_dashb_categor_3f9b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsettings',
            index=models.Index(fields=['is_public'], name='admin_dashb_is_publ_f7fb01_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'created_at'], name='admin_dashb_report__5ed1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='admin_dashb_status_8b70dc_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'created_at'], name='admin_dashb_generat_c64b96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('name', 'template_type')},
        ),
        migrations.AddIndex(
            model_name='platformanalytics',
            index=models.Index(fields=['date'], name='admin_dashb_date_e1ca5c_idx'),
        ),
    ]
