# Generated by Django 5.2.7 on 2026-01-01 02:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base price for this category', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Platform commission percentage', max_digits=5)),
                ('min_duration', models.IntegerField(default=15, help_text='Minimum consultation duration in minutes')),
                ('max_duration', models.IntegerField(default=120, help_text='Maximum consultation duration in minutes')),
                ('available_24_7', models.BooleanField(default=False, help_text='Whether this service is available 24/7')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='medium', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('professional_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('professional_notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('call_start_time', models.DateTimeField(blank=True, null=True)),
                ('call_end_time', models.DateTimeField(blank=True, null=True)),
                ('call_duration', models.IntegerField(default=0, help_text='Actual call duration in minutes')),
                ('client_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('client_review', models.TextField(blank=True, null=True)),
                ('professional_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professional_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_attempts', models.IntegerField(default=0)),
                ('is_urgent', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='web', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='accounts.professionalprofile', verbose_name='Professional')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='categories.servicecategory', verbose_name='Service Category')),
            ],
            options={
                'verbose_name': 'Consultation Request',
                'verbose_name_plural': 'Consultation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='consultation_messages/%Y/%m/%d/')),
                ('attachment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_messages', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='categories.consultationrequest')),
            ],
            options={
                'verbose_name': 'Consultation Message',
                'verbose_name_plural': 'Consultation Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultation_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='categories.consultationrequest')),
            ],
            options={
                'verbose_name': 'Consultation Attachment',
                'verbose_name_plural': 'Consultation Attachments',
            },
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['status', 'created_at'], name='categories__status_8a83d8_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['client', 'status'], name='categories__client__7721de_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['professional', 'status'], name='categories__profess_6bcb56_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['category', 'status'], name='categories__categor_b67048_idx'),
        ),
    ]
